name: SwiftFormat

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  swiftformat:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install SwiftFormat
        run: brew install swiftformat

      - name: Run SwiftFormat
        run: swiftformat .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply SwiftFormat changes
          file_pattern: "*.swift"
